### ISSUE TITLE
Overall semantics/formatting/filenames

### ISSUE THREAD

**Issue by vr8hub** [kingrpaul/algernon-blackwood_short-fiction#1]
1. In content.opf, the contributer info should be grouped by contributor. For example, everything for a transcriber: name, file-as, roles, etc. should be grouped together for a single transcriber. And so forth.
2. The top block-level should be article, not section, for short-stories (see section 4.1.1 in the manual, specifically [4.1.1.1.3](https://standardebooks.org/manual/1.1.1/4-semantics#4.1.1.1.3)).
3. The top-level epub:type for short-stories is se:short-story, not chapter.
4. Some of the filenames still don't match their id's, e.g. simon-parnacute.xhtml vs the-eccentricity-of-simon-parnacute, etc. As mentioned on the list, the id's and filenames should be the same, and should be the url-safe version of the title.
5. There are several pieces of the poetry CSS missing, e.g. what's in 7.5.1-.3 of the manual. (And maybe 7.5.4; I haven't looked at every one to see if there was any indenting on any of them.)
6. I don't remember if the manual explicitly says this, but "z3998:poem" is for an entire poem, and "z3998:verse" is for portions of a poem. Most of the ones I saw appear to be partial, and so should be "verse". If you end up with a mixture, then you'll need the CSS for both.

**Comment by kingrpaul** [comment]
- [ ] In content.opf, the contributer info grouped by contributor
- [ ] The top block-level articles
- [ ] The top-level epub:type se:short-story
- [ ] Filenames still match id's
- [ ] Pieces of the poetry CSS missing
- [ ] "z3998:poem" for entire poem, "z3998:verse" is for portions of a poem

**Comment by kingrpaul** [comment]
https://github.com/kingrpaul/algernon-blackwood_short-fiction/commit/4232f2b1e43070db1f0df5cd35bd64936dc2a926
