### ISSUE TITLE
First batch of issues

### ISSUE THREAD

**Issue by weijia-cheng** [kingrpaul/algernon-blackwood_short-fiction#1]
Working through the step by step review process; this is the first batch of issues I found

# Typography

- [x] Changes made by `se typogrify` on `content.opf` and `summering-in-canadian-backwoods.xhtml` should be accepted.
- [x] Revert b22a2a13fac874d790906aae3b7e622bc3ebf003. Per Chicago 7.15, “the possessive of most *singular* nouns is formed by adding an apostrophe and an *s*” (without exception for words ending in *s*). Per 7.16, “the general rule extends to proper nouns, including names ending in *s*.” 7.21 notes specifically that the practice of omitting the possessive *s* on all words ending in *s* is not recommended by Chicago. SEMOS does not contain rules on possessives so we default to following the Chicago rules.
- [x] `se clean` seems to be changing some whitespaces in the lint ignore file, which you should accept.

# Spelling

- [x] Running `se modernize-spelling` creates several valid changes. Pretty much all of them look good from me apart from the ones that are trying to change `may-day` to `mayday` in an `id`.
- [x] I see several valid changes coming from `se semanticate`. I want to point out in particular that in some lines of `sambo-and-snitch.xhtml` you have a valid `eoc` class being added while bogus Roman numeral semantics are also being added. You’ll still want to add the `eoc` though the Roman numeral semantics should be discarded.
- [x] The one instance of “a-quiver” should be modernized to “aquiver”

# Misc

- [x] Remove `readme.md`, which is not a valid file in an SE project.

**Comment by kingrpaul** [comment]
5550fe513d3a664760d3c211148ee93ec455a882
