### ISSUE TITLE
Proofreading

### ISSUE THREAD

**Issue by vr8hub** [kingrpaul/algernon-blackwood_short-fiction#2]
Overall, this looks like a nice production, but I'm going to suggest another proofing run or two through all of the stories before we go any further. Here are a few examples of things I found just looking at a few stories.

**Man Who Trees Loved**
1. The two block quotes right next to each other (pp 22-23) quoting from a poem should be a single blockquote. The five asterisks (or whatever those are) in the scans are an indication of vertical elision, i.e. skipping lines in-between what is quoted, and should be formatted accordingly. See section [7.5.7](https://standardebooks.org/manual/1.1.1/7-high-level-structural-patterns#7.5.7) of the manual.
2. The `<hr/>'s` in the story don't match the scans, i.e. there are breaks (blank lines between paragraphs) in the story that don't have `<hr/>'s` in the file, and there are `<hr/>'s` in the file that don't correspond to breaks in the story.
3. There is at least one instance of a runaway italic—_please do not throw away your cigars…_ Only the "please" should be italicized.

**The Eccentricity of Simon Paranacute**
1. Missing italics, e.g. _lovely songsters_, "do the birds know _this_…", etc.
2. Missing or mis-formed ellipses, e.g. "It came, as it were, through barriers . .".
3. Italics (whether `<i>` or `<em>`) should be inside quote-marks, e.g. "_Sings his wild note_…".

**Carlton's Drive**
1. Missing italics, e.g. _pushing it_….

**Temptation of the Clay**
1. Several missing abbreviations, e.g. the `C.` in `John C.` in multiple places.

These are the kind of things to look for in every story—are the breaks correct, are all the italics present and correct (and semanticated, where needed), are there mis-formed ellipses, are block quotes (of whatever kind) formatted and semanticated correctly, are foreign words not in M-W semanticated and italicized, are foreign words in M-W _not_ italicized, and so forth.

I know proofing is time-consuming and difficult, and I know we're never going to catch everything, but we want to catch _most_ things before we release it to the public. I feel your pain—it took me 5 months to produce O. Henry's short fiction collection, and I just had to go page-by-page comparing 1000+ pages of _Tom Jones_ to the scans, **twice.** :)

Let me know when you're finished, and I'll start anew. Thanks for your work on this, Paul!

**Comment by kingrpaul** [comment]
**Man Who Trees Loved**
- [ ] The two block quotes right next to each other (pp 22-23) quoting from a poem should be a single blockquote. The five asterisks (or whatever those are) in the scans are an indication of vertical elision, i.e. skipping lines in-between what is quoted, and should be formatted accordingly. See section [7.5.7](https://standardebooks.org/manual/1.1.1/7-high-level-structural-patterns#7.5.7) of the manual.
- [ ] The `<hr/>'s` in the story don't match the scans, i.e. there are breaks (blank lines between paragraphs) in the story that don't have `<hr/>'s` in the file, and there are `<hr/>'s` in the file that don't correspond to breaks in the story.
- [ ] There is at least one instance of a runaway italic—_please do not throw away your cigars…_ Only the "please" should be italicized.

**The Eccentricity of Simon Paranacute**
- [ ] Missing italics, e.g. _lovely songsters_, "do the birds know _this_…", etc.
- [ ] Missing or mis-formed ellipses, e.g. "It came, as it were, through barriers . .".
- [ ] Italics (whether `<i>` or `<em>`) should be inside quote-marks, e.g. "_Sings his wild note_…".

**Carlton's Drive**
- [ ] Missing italics, e.g. _pushing it_….

**Temptation of the Clay**
- [ ] Several missing abbreviations, e.g. the `C.` in `John C.` in multiple places.

**Comment by kingrpaul** [comment]
> 
> 
> Overall, this looks like a nice production, but I'm going to suggest another proofing run or two through all of the stories before we go any further. Here are a few examples of things I found just looking at a few stories.
> 
> **Man Who Trees Loved**
> 
>     1. The two block quotes right next to each other (pp 22-23) quoting from a poem should be a single blockquote. The five asterisks (or whatever those are) in the scans are an indication of vertical elision, i.e. skipping lines in-between what is quoted, and should be formatted accordingly. See section [7.5.7](https://standardebooks.org/manual/1.1.1/7-high-level-structural-patterns#7.5.7) of the manual.
> 
>     2. The `<hr/>'s` in the story don't match the scans, i.e. there are breaks (blank lines between paragraphs) in the story that don't have `<hr/>'s` in the file, and there are `<hr/>'s` in the file that don't correspond to breaks in the story.
> 
>     3. There is at least one instance of a runaway italic—_please do not throw away your cigars…_ Only the "please" should be italicized.
> 
> 
> **The Eccentricity of Simon Paranacute**
> 
>     1. Missing italics, e.g. _lovely songsters_, "do the birds know _this_…", etc.
> 
>     2. Missing or mis-formed ellipses, e.g. "It came, as it were, through barriers . .".
> 
>     3. Italics (whether `<i>` or `<em>`) should be inside quote-marks, e.g. "_Sings his wild note_…".
> 
> 
> **Carlton's Drive**
> 
>     1. Missing italics, e.g. _pushing it_….
> 
> 
> **Temptation of the Clay**
> 
>     1. Several missing abbreviations, e.g. the `C.` in `John C.` in multiple places.
> 
> 
> These are the kind of things to look for in every story—are the breaks correct, are all the italics present and correct (and semanticated, where needed), are there mis-formed ellipses, are block quotes (of whatever kind) formatted and semanticated correctly, are foreign words not in M-W semanticated and italicized, are foreign words in M-W _not_ italicized, and so forth.
> 
> I know proofing is time-consuming and difficult, and I know we're never going to catch everything, but we want to catch _most_ things before we release it to the public. I feel your pain—it took me 5 months to produce O. Henry's short fiction collection, and I just had to go page-by-page comparing 1000+ pages of _Tom Jones_ to the scans, **twice.** :)
> 
> Let me know when you're finished, and I'll start anew. Thanks for your work on this, Paul!

Thank you for the review -- it's very much a learning process and seemed a smaller project when I started. - Paul

**Comment by vr8hub** [comment]
No problem. It took me several books before I felt comfortable, and they still manage to find things I missed in the reviews of my productions. And yes, I've started a few books thinking they wouldn't be too big a deal, and discovered I was very wrong. :)

Let me know when you're finished proofing everything (as I mentioned, the above are just examples) and I'll take a look again.

**Comment by kingrpaul** [comment]
https://github.com/kingrpaul/algernon-blackwood_short-fiction/commit/596056077b3a548bb02714b2ee501ba6c1ff78fe
