### ISSUE TITLE
Foreign language

### ISSUE THREAD

**Issue by vr8hub** [kingrpaul/algernon-blackwood_short-fiction#7]
- [x] 1. There are language tags on words/phrases that appear in Merriam-Webster, e.g. "per se" in Victim of Higher Space. See [section 8.2.9](https://standardebooks.org/manual/1.2.0/8-typography#8.2.9) of the manual (same for section for all of these). There are a number of others, you'll need to check them all. (Don't make the mistake I consistently make: "Oh, I don't need to check that one, it's definitely not in there"; I'm amazed at how often it is.)

- [x] 2. There are some Latin tags on taxonomy; that should be tagged as abbreviations with class taxonomy; see the abbreviation section in the manual.

- [x] 3. The two-character language code for German is "de", not "ge"; see [here](http://www.loc.gov/standards/iso639-2/php/code_list.php) as just one example. (I think the list is also on Wiki.)

- [x] 4. There is non-English language text that is neither italicized nor tagged, e.g. "Enfin! M’sieur s’est…" in Ancient Sorceries.

- [x] 5. The language tags are all missing xml:, i.e. it's `xml:lang="xx"`, not `lang="xx"`.

- [x] 6. There are uppercase language tags; they should all be lowercase.

- [x] 7. There a few occurrences of three-character language codes; they should all be two-character.

- [x] 8. The "sumpfe" in The Willows appears to be German, not Hungarian. (I speak neither, but I generally trust Google Translate in these situations, plus a quick web search confirmed. It generally has an umlaut over the u, but I'm guessing the source scan didn't have it, which is fine.)

- [x] 9. I believe there's more to tagging romanized Chinese than just the zh, and I'm not sure those should even be tagged. But I _definitely_ don't speak Chinese. :) However, there are a couple of native speakers on the list now, so you might ask there.

- [x] 10. The _Tannhäuser_ in Victim of Higher Space is an opera and should be tagged as such rather than as a foreign language word. See section [8.2.11.2](https://standardebooks.org/manual/1.2.0/8-typography#8.2.11.2) of the manual. Please check the others as well. (Capitalized words are usually a good hint, especially single ones.)

**Comment by kingrpaul** [comment]
"sumpfe": from text and map, concluded Hungary, thus Hungarian -> appears mistaken

**Comment by kingrpaul** [comment]
Best guess, "bersim" is French -> https://dictionary.reverso.net/french-definition/bersim

**Comment by kingrpaul** [comment]
@vr8hub so ... words italicized in the original such as "per se" that are in the dictionary have those italics removed?

**Comment by vr8hub** [comment]
That's why I linked to the manual. :) Yes, per 8.2.9.4, "Words and phrases that are originally non-English in origin, but that can now be found in Merriam-Webster, are not italicized."

**Comment by kingrpaul** [comment]
> 
> 
> That's why I linked to the manual. :) Yes, per 8.2.9.4, "Words and phrases that are originally non-English in origin, but that can now be found in Merriam-Webster, are not italicized."

Thanks.

**Comment by vr8hub** [comment]
Just for the record, #7 was correct for this production but TIL not in general. There are languages that do not have two-digit codes, in which case we use the three-character one. But we always use the two-character one if the language has one.
