### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by vr8hub** [kingrpaul/algernon-blackwood_short-fiction#8]
- [x] 1. The use of châlet vs. chalet is inconsistent in the stories; two use the former, one the latter. It may be that way in the source, but even if so, I wonder if we should be consistent, and whether we need the circumflex that is no longer used. Thoughts, @acabal?

- [x] 2. The [link](https://archive.org/details/dayandnightstori45964gut) you have for _Day and Night Stories_ only contain pictures of the covers, not actual scans of the book pages. I found [this](https://archive.org/details/dayandnightstori00blacrich), but what did you use to proofread the contained stories against? Pleae make sure all of the other scan links contain page scans of the books.

**Comment by acabal** [comment]
We can remove the circumflex from chalet as a modernization if it does not refer to a proper name or actual French text. `se find-mismatched-diacritics` is useful for spotting things like this.

**Comment by vr8hub** [comment]
Yes, that's actually how I found this.

**Comment by kingrpaul** [comment]
Day and Night Stories: https://archive.org/details/dayandnightstor00blacgoog --working from a local PDF.

**Comment by vr8hub** [comment]
That one is great, it's just not the one you have listed in content.opf. That one doesn't have the pages.
